create TABLE wps_app_data.wps (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    manufacturer VARCHAR(255),
    inspection_agency VARCHAR(255),
    wpqr INT DEFAULT NULL,
    cleaning VARCHAR(255),
    weld_proc INT,
    weld_type VARCHAR(255),
    welding_position VARCHAR(255),
    filler_material VARCHAR(255),
    material_thickness1 FLOAT,
    material_thickness2 FLOAT,
    outside_diameter1 FLOAT,
    outside_diameter2 FLOAT,
    backing_gas VARCHAR(255),
    backing_gas_flow_rate FLOAT,
    specification_of_base_material VARCHAR(255),
    group_of_additional_material VARCHAR(255),
    img_welding_design VARCHAR(255),
    img_welding_technique VARCHAR(255),
    weld_size FLOAT,
    note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (wpqr) REFERENCES wpqr(id)
);